### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by 90N45-d3v** [nototter/pwnhyve#6]
I haven't tested your project yet, but you wrote that you need help with the front-end. I would love to help you...

Can you tell me what exactly you need help with? You said the design was really ugly, so you already got the backend working? If it's just the HTML/CSS design or something like that, I could build it without having to setup my Raspberry again.

**Comment by nototter** [comment]
yes, i believe it's just the front end that needs work - back end still needs a little work but once thats done i will gladly take your help
do you have any way to directly contact you? telegram, discord, etc.
thank you so much btw

**Comment by 90N45-d3v** [comment]
Sure, you can hit me on Discord: 90N45#1983
I think with this, you can close the issue 👍
